### ISSUE TITLE
This is not an issue but a question!

### ISSUE THREAD

**Issue by PMARZV** [tminet/API-Request#11]
Im developing another app that is pretty similar in the way its structured. When you arrive to the photos fragment, how do you preserve the data of the previous fragments in backstack without making another api call? And also if there was several photos fragments but with different contents (same fragment, two different instances in backstack), how do i keep the data of all of them when going back to these fragments stored in the backstack but with same structure fragment but different data? im not using compose btw. I would like an explanation on this because ive been stuck for several weeks now. im a starter on dev but ive been trying to look for similar code like your and trying to understand it but i dont find the exact answer.....😥

**Comment by tminet** [comment]
It's kinda hard to explain because it's been a long time since I've used the `Fragment` navigation methods with the `XML Graph`, but I don't remember having any secrets, since the [navigation library](https://developer.android.com/guide/navigation/get-started) should handle this automatically for us...

You can take a look at the [old commit tree](../tree/c492a02d3db1dbe5a0cc137aaa13ebf50266c955/app/src/main/java/tmidev/apirequest) before it was migrated to `Compose`, maybe this code can guide you.

Also, if you want, share a repository with your current code. I won't be sure to solve your problem, but I'll try to guide you based on what you have. Or even better, you can create a question on [StackOverflow](https://stackoverflow.com), just detail your problem and put part of the current code, I can answer there, and if I can't, other people can show up to help you too.
